events {
  worker_connections 1024;
}

http {
  upstream frontend {
    server frontend:3000;
  }

  upstream strapi {
    server strapi:1337;
  }

  upstream minio {
    server minio:9000;
  }

  server {
    listen 80;
    server_name localhost;

    # Frontend
    location / {
      proxy_pass http://frontend;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }

    # Strapi API
    location /strapi/ {
      rewrite ^/strapi/(.*)$ /$1 break;
      proxy_pass http://strapi;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # MinIO
    location /storage/ {
      rewrite ^/storage/(.*)$ /$1 break;
      proxy_pass http://minio;
      proxy_set_header Host $host;
    }
  }
}
